### ISSUE TITLE
Issue with the down+merge

### ISSUE THREAD

**Issue by proxygod** [R00t173/BaiskoafuDown#1]
It has an issue when I download larger files. I've tried with two large videos (movies) and both of which came corrupt & unplayable.

You could try downloading "Bos" and see.

Would be great if there's a fix ;)

**Comment by DeLuffy** [comment]
prolly due to drm encryption in them, Cant u try n make a modified vertion
of this app, that can be used as like possibility of screen shot,screen
recording or even usable in emulator, it will be easier then. I've seen
many developer s trying to get the content still stuck with the m3u8 url
they need to decrypt the key that used for encrypting it😕. well looking
forward to hear from you soon

**Comment by proxygod** [comment]
That would need an emulator bypass for the app itself. It's possible but the python version could be more handy. Just need a fix for split & merge I guess.

**Comment by DeLuffy** [comment]
Aight do look for a fix,i really like this, hope for a fix soon👍

**Comment by DeLuffy** [comment]
Does this rings a bell? after getting the encrypted keys😑

**Comment by proxygod** [comment]
I have fixed it and reuploaded it: https://github.com/proxygod/BaiskoafuDown.git

:)
